### ISSUE TITLE
Check for usage of config.no_cache

### ISSUE THREAD

**Issue by tmotyl** [martin-helmich/typo3-typoscript-lint#102]
It would be awesome if linter could warn user on every `config.no_cache =1` usage.
Instead of setting setting config.no_cache one should use USER_INT.
using config.no_cache is 5x slower than USER_INT (in scenarios where multiple concurent request are comming). This is due too fact that no_cache is locking cache for writing, but at the end no cache entry is generated, so multiple requests are waiting on each other.

**Comment by martin-helmich** [comment]
Fixed in #105
