### ISSUE TITLE
Tokenization error when overriding BE template paths

### ISSUE THREAD

**Issue by fnagel** [martin-helmich/typo3-typoscript-lint#175]
When using something like `templates.typo3/cms-dashboard.1700145317 = felixnagel/t3extblog:Resources/Private` in order to override template paths in BE (as described [here](https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/12.0/Breaking-96812-NoFrontendTypoScriptBasedTemplateOverridesInTheBackend.html)) an error is thrown: `Tokenization error: Cannot tokenize line "templates.typo3/cms-dashboard.1700145317 = felixnagel/t3extblog:Resources/Private"`

**Comment by martin-helmich** [comment]
Sorry this took a while. This should be fixed with https://github.com/martin-helmich/typo3-typoscript-parser/pull/98.

**Comment by fnagel** [comment]
Thank you! In my use case, its fixed: https://github.com/fnagel/t3extblog/commit/62b19a0d89cab03f28be50dc8b1ac8223028e96c
