### ISSUE TITLE
Restrict to TypoScript files

### ISSUE THREAD

**Issue by mbrodala** [martin-helmich/typo3-typoscript-lint#19]
Right now arbitrary files/directories can be passed to the lint command. This lets the linter check non-TypoScript files too which is undesired.

Thus the linter should restrict itself to TypoScript files by default which can be achieved with file extension/file name pattern checks. I'd suggest the following list:

- `*.ts`
- `*.typoscript`
- `constants.txt`
- `setup.txt`
- `ext_typoscript_constants.txt`
- `ext_typoscript_setup.txt`
- `ext_conf_template.txt`

If possible/necessary this could be customizable with a CLI argument and `tslint.yml` option.

**Comment by martin-helmich** [comment]
@mbrodala, this is a good idea. I'm still trying to think of a way to build this without breaking backwards compatibility. My current favorite would be to implement this feature, but continue to lint _all_ files by default when no file pattern list was configured in the config file. What do you think?

**Comment by mbrodala** [comment]
Sounds reasonable and thanks for implementing this. Again, looking forward to the next release. ;-)
