### ISSUE TITLE
"tslint.yml" might not be a good default name

### ISSUE THREAD

**Issue by atomicptr** [martin-helmich/typo3-typoscript-lint#60]
The default Typ**e**Script linter tslint is using the exact same name and also (can) share the filename. This causes a conflict by default because we already had a "tslint.yml" in our project, which typoscript-lint tried to read. Obviously using a different name and telling the linter to use that file (via -c) instead solves this issue, but this can be confusing nonetheless. Another reason might be that the default file extension for TypoScript files is now *.typoscript or *.tsconfig and not *.ts.

**Comment by martin-helmich** [comment]
True, indeed. However, changing this is going to be pain, as it might break a few people's workflow. Let me see if I can come up with some backwards-compatible way to change this.
