### ISSUE TITLE
symfony/console dependency breaking TYPO3 9.5 support

### ISSUE THREAD

**Issue by saitho** [martin-helmich/typo3-typoscript-lint#87]
Hey there,

I just wanted to check out master for the new "Allow right values" feature.
I noticed that it uses `symfony/console` ^5.0. This effectively breaks support for TYPO3 9.5:

>  typo3/cms-core v9.5.13 requires symfony/console ^4.1

**Comment by martin-helmich** [comment]
Ugh. I had feared something like this might happen... :see_no_evil: Thanks for the report - I'll check this out shortly.

**Comment by martin-helmich** [comment]
Thanks for the report -- I've downgraded again to Symfony 3 and/or 4 for the time being in #90. This should restore master (and the upcoming releases) back to a working state. Unfortunately, as long as you're extending the `Symfony\Component\Config\Loader\FileLoader` class somewhere in your code, there does not seem to be a way to be compatible to *both* Symfony 3/4 and 5.
