### ISSUE TITLE
Update symfony components to use version 5

### ISSUE THREAD

**Issue by spoonerWeb** [martin-helmich/typo3-typoscript-lint#98]
As TYPO3 CMS core (version 10) is requiring symfony components in either v4 or v5 (of course it used v5), it's not possible to install the linter.
Please update the linter to handle version 5 of the symfony components as well.

**Comment by martin-helmich** [comment]
Thanks for the hint. I'm not sure when I'll get to this - PRs are welcome in the meantime.

**Comment by echavaillaz** [comment]
Yes with this package installed, not possible to update to TYPO3 10.4.7.

Thanks,
Eric

**Comment by martin-helmich** [comment]
Alternative suggestion for escaping dependency hell: you can use the PHAR version (which can optionally be installed via Phive)

**Comment by peterkraume** [comment]
TYPO3 v10.4.7 had a misconfigured composer-dependency (so composer-based TYPO3 installations could not upgrade). Benni published v10.4.8 today to mitigate this issue. TYPO3 v9 installations and TYPO3 v10 installations in non-composer-mode (downloading the zip file) are not affected. https://typo3.org/article/typo3-1047-and-9521-maintenance-releases-published

**Comment by echavaillaz** [comment]
Yes now it works fine.

Thanks.
Eric
